import { useState } from "react";


function Accordion_sm() {
    const [activeDefault, setActiveDefault] = useState(0);
    const defaultAccordion = [
        {
            title: "Why is SEO important?",
            text:
                "Search engine optimization brings organic traffic to your site. Users trust search engines, and achieving a top spot in search engine rankings signals to searchers that your site is a credible source. The higher you rank in results pages, the more clicks and traffic your site will generate. SEO also improves user experience, making it more likely for customers to become repeat buyers.",
            bg: "primary",
        },
        {
            title: "How Search Engines Work ?",
            text:
                "The fundamental aim of search engines is to satisfy their users. They want to provide the best results when a user searches for something.  SEO is Google’s way of determining which sites deserve to rank highly for each query entered into its search engine. Without modern SEO, it would be extremely simple to manipulate the search results so that the site with the most links or the most pages—all easily generated by software—consistently ranked #1.",

            bg: "info",
        },
        {
            title: "What can our SEO services do ?",
            text:
                "Donec suscipit porta lorem eget condimentum. Morbi vitae mauris in leo venenatis varius. Aliquam nunc enim, egestas ac dui in, aliquam vulputate erat. Curabitur porttitor ante ut odio vestibulum, et iaculis arcu scelerisque.Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.",

            bg: "success",
            
        },
       
       
        
    ];
  return (
    <>
        <div
            className="dlab-accordion accordion-sm"
            id="accordionFaq"
            defaultActiveKey="0"
        >
            {defaultAccordion.map((d, i) => (
                <div className="card" key={i}>
                    <div
                        eventKey={`${i}`}
                        className="card-header"
                        onClick={() =>
                            setActiveDefault(activeDefault === i ? -1 : i)
                        }
                    >
                        <h5 className="dlab-title">
                            <a href="#"
                                className={`${
                                    activeDefault === i ? "" : "collapsed"
                                }`}
                                onClick={() =>
                                    setActiveDefault(
                                        activeDefault === i ? -1 : i
                                    )
                                }
                            >
                                {" "}
                                {d.title}
                            </a>
                        </h5>
                    </div>
                    {/* <div className="collapse show" eventKey={`${i}`}>
                        <div className="card-body">
                            <p className="m-b0">{d.text}</p>
                        </div>
                    </div> */}
                    <div className={`${
                                    activeDefault === i ? "collapsed show" : "collapsed"
                                }`} eventKey={`${i}`} onClick={() =>
                                    setActiveDefault(
                                        activeDefault === i ? -1 : i
                                    )
                                }>
                        <div className="card-body">
                            <p className="m-b0">{d.text}</p>
                        </div>
                        </div>
                </div>
            ))}
        </div>
    </>
  )
}

export default Accordion_sm;